# Generated by Django 3.1.3 on 2020-11-07 06:37

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('paths', jsonfield.fields.JSONField(max_length=200)),
                ('library_type', models.CharField(choices=[('MOVIE', 'Movie'), ('OTHER', 'Other'), ('TV', 'Tv')], default='OTHER', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TvShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_server.medialibrary')),
            ],
        ),
        migrations.CreateModel(
            name='TvSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_index', models.IntegerField(default=0)),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_server.tvshow')),
            ],
        ),
        migrations.CreateModel(
            name='TvEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_index', models.IntegerField(default=0)),
                ('tv_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_server.tvseason')),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_server.tvshow')),
            ],
        ),
    ]
