# Generated by Django 3.1.3 on 2020-11-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvepisode',
            name='filepath_temp',
            field=models.CharField(default='', max_length=200),
        ),
    ]
