# Generated by Django 3.1.3 on 2020-11-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0004_mediafile_tv_episode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvepisode',
            name='versions',
        ),
    ]
