# Generated by Django 3.1.3 on 2020-11-12 20:23

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0007_auto_20201112_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvShowDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backdrop_path', models.CharField(max_length=200)),
                ('first_air_date', models.CharField(max_length=200)),
                ('last_air_date', models.CharField(max_length=200)),
                ('genres', jsonfield.fields.JSONField(default=[])),
                ('tmdb_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('overview', models.CharField(max_length=200)),
                ('poster_path', models.CharField(max_length=200)),
                ('production_companies', jsonfield.fields.JSONField(default=[])),
                ('type', models.CharField(max_length=200)),
                ('vote_average', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.AlterField(
            model_name='medialibrary',
            name='paths',
            field=jsonfield.fields.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='details',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='media_server.tvshowdetails'),
        ),
    ]
