# Generated by Django 3.1.3 on 2020-11-12 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0008_auto_20201112_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvshow',
            old_name='details',
            new_name='details_id',
        ),
    ]
