# Generated by Django 3.1.3 on 2020-11-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0009_auto_20201112_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshowdetails',
            name='first_air_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tvshowdetails',
            name='last_air_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
