# Generated by Django 3.1.3 on 2020-11-12 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0011_auto_20201112_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvshow',
            old_name='details_id',
            new_name='tv_show_details',
        ),
    ]
