# Generated by Django 3.1.3 on 2020-11-12 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0012_auto_20201112_1557'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TvShowDetails',
            new_name='TvShowDetail',
        ),
    ]
