# Generated by Django 3.1.3 on 2020-11-12 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0014_auto_20201112_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshowdetail',
            name='tv_show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_server.tvshow'),
        ),
    ]
