# Generated by Django 3.1.3 on 2020-11-12 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0016_auto_20201112_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshow',
            name='tv_show_details',
        ),
    ]
