# Generated by Django 3.1.3 on 2020-11-12 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0017_remove_tvshow_tv_show_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvSeasonDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_date', models.DateField(default=None, null=True)),
                ('name', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('tmdb_id', models.IntegerField()),
                ('poster_path', models.CharField(max_length=200)),
                ('season_number', models.IntegerField()),
                ('tv_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_server.tvseason')),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_server.tvshow')),
            ],
        ),
        migrations.CreateModel(
            name='TvEpisodeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_date', models.DateField(default=None, null=True)),
                ('episode_number', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('tmdb_id', models.IntegerField()),
                ('production_code', models.CharField(max_length=200)),
                ('still_path', models.CharField(max_length=200)),
                ('vote_average', models.FloatField()),
                ('tv_episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_server.tvepisode')),
                ('tv_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_server.tvseason')),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_server.tvshow')),
            ],
        ),
    ]
