# Generated by Django 3.1.3 on 2020-11-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0018_tvepisodedetail_tvseasondetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvepisodedetail',
            name='sort_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvshow',
            name='sort_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvshowdetail',
            name='sort_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
