# Generated by Django 3.1.3 on 2020-11-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0019_auto_20201113_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvepisodedetail',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tvepisodedetail',
            name='still_path',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tvseasondetail',
            name='poster_path',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tvshowdetail',
            name='backdrop_path',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tvshowdetail',
            name='poster_path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
