# Generated by Django 3.1.3 on 2020-11-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0020_auto_20201113_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('args', models.TextField()),
                ('start_time', models.DateTimeField()),
            ],
        ),
    ]
