# Generated by Django 3.1.3 on 2020-11-20 14:49

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0022_streamprocess_media_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='HlsProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hls_id', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('media_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_server.mediafile')),
            ],
        ),
        migrations.AddField(
            model_name='tvepisodedetail',
            name='tv_season_detail',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='media_server.tvseasondetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvepisodedetail',
            name='tv_show_detail',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='media_server.tvshowdetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvseasondetail',
            name='tv_show_detail',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='media_server.tvshowdetail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tvshowdetail',
            name='backdrop_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tvshowdetail',
            name='first_air_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tvshowdetail',
            name='genres',
            field=jsonfield.fields.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='tvshowdetail',
            name='last_air_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tvshowdetail',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tvshowdetail',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tvshowdetail',
            name='poster_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tvshowdetail',
            name='production_companies',
            field=jsonfield.fields.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='tvshowdetail',
            name='sort_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tvshowdetail',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tvshowdetail',
            name='type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tvshowdetail',
            name='vote_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='StreamProcess',
        ),
    ]
