# Generated by Django 3.1.3 on 2020-11-20 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0023_auto_20201120_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hlsprocess',
            name='hls_id',
        ),
        migrations.AddField(
            model_name='hlsprocess',
            name='last_poll',
            field=models.DateTimeField(default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
