# Generated by Django 3.1.3 on 2020-11-20 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0024_auto_20201120_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('last_poll', models.DateTimeField(null=True)),
                ('media_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_server.mediafile')),
            ],
        ),
        migrations.DeleteModel(
            name='HlsProcess',
        ),
    ]
